In [1]:
import pandas as pd

In [3]:
AA = pd.read_csv('AA_4_24_2018.csv')

In [4]:
AA.head()

   Student_ID                        Email
0    31014572          nz1012861@gmail.com
1    31250486     ryanfagostinho@gmail.com
2    31319249  student979student@gmail.com
3    31388101  hermanfernandez14@gmail.com
4    31399639       kgkandel@optonline.net

In [5]:
Tested_reg = pd.read_csv('tested_reg_4_24_2018.csv')

In [6]:
Tested_reg.head()

   Student_ID
0    31471102
1    31447906
2    31454600
3    31449835
4    31460437

In [7]:
AA

     Student_ID                               Email
0      31014572                 nz1012861@gmail.com
1      31250486            ryanfagostinho@gmail.com
2      31319249         student979student@gmail.com
3      31388101         hermanfernandez14@gmail.com
4      31399639              kgkandel@optonline.net
5      31399786          maranoncarlos126@gmail.com
6      31401330               julianalsch@gmail.com
7      31401497          akrampanther2018@gmail.com
8      31402858                tleonard18@pthsd.net
9      31411728               chrisskchia@yahoo.com
10     31412989                  gus94369@gmail.com
11     31414234              snaito@ucvts.tec.nj.us
12     31414441  capicchioni.applications@gmail.com
13     31414493               tigersean08@yahoo.com
14     31414876               shaheedfive@gmail.com
15     31416053           reeshagandhi123@gmail.com
16     31416764             remembrance70@gmail.com
17     31416769               frisky2k_26@yahoo.com
18     31416966          simonpfontanilla@gmail.com
19     31417882              karolinka456@yahoo.com
20     31420345                 robnguyen@yahoo.com
21     31420429                    bkbkfk@yahoo.com
22     31420429                    bkbkfk@yahoo.com
23     31420504              cecarson@optonline.net
24     31422370                 mbanos107@gmail.com
25     31422372                avanibudoo@gmail.com
26     31427523           nikhilsinha1212@gmail.com
27     31427575             gilloyd.embar@gmail.com
28     31428386       prescottandrew@rocketmail.com
29     31428867                 etcasuple@gmail.com
..          ...                                 ...
686    31473277                  westfarr@gmail.com
687    31473655             maxecohen2001@gmail.com
688    31473795              bbhuiyan3180@gmail.com
689    31473795              bbhuiyan3180@gmail.com
690    31473940                 vicocinio@gmail.com
691    31474011            amandamariem09@gmail.com
692    31474162                  dancd100@gmail.com
693    31474344               tahayounis3@gmail.com
694    31474347                 wbondiv12@gmail.com
695    31474634                judyzuo124@gmail.com
696    31474722                1jamescoll@gmail.com
697    31474732               legoman9994@gmail.com
698    31474754             simerpreets95@gmail.com
699    31475100                 anmorales@ctemc.org
700    31475147              dreamville80@gmail.com
701    31475168              randyzam2899@gmail.com
702    31476114              ammadbajwa77@gmail.com
703    31476400               chan.alan11@gmail.com
704    31476527              skallimariam@gmail.com
705    31476628              gian.ordonez@gmail.com
706    31476635        ghanshyampatel123r@gmail.com
707    31476700                cosmicpm24@gmail.com
708    31476726             bendejesus123@gmail.com
709    31477267             amaan.rajguru@gmail.com
710    31477380      avshalom.israel.sela@gmail.com
711    31477529              whyandwonder@yahoo.com
712    31477621                jcranmer34@gmail.com
713    31477657           antoniousshaker@gmail.com
714    31477698     181117@edu.bloomfield.k12.nj.us
715    31477870                   fuschc4@gmail.com

[716 rows x 2 columns]

In [8]:
Tested_reg

     Student_ID
0      31471102
1      31447906
2      31454600
3      31449835
4      31460437
5      31462195
6      31433683
7      31458778
8      31464247
9      31430110
10     31466613
11     31447363
12     31454117
13     31433756
14     31467112
15     31466982
16     31458296
17     31469639
18     31458461
19     31456634
20     31454427
21     31470958
22     31441601
23     31455970
24     31459516
25     31458855
26     31454828
27     31450298
28     31447389
29     31437049
..          ...
404    31430605
405    31470572
406    60900432
407    31435770
408    31435770
409    31465449
410    31450523
411    31446993
412    31468413
413    31453362
414    31449859
415    31452750
416    31469597
417    31456951
418    31461857
419    31464703
420    31435759
421    31471638
422    31429298
423    31442634
424    31420345
425    31452127
426    31452151
427    31437002
428    31464903
429    31464255
430    31462273
431    31447295
432    31466635
433    31459772

[434 rows x 1 columns]

In [11]:
online=pd.read_csv('online.csv')

In [12]:
online

         S_ID
0    31449881
1    31465444
2    31460460
3    31432203
4    31464512
5    31449804
6    31472274
7    31460759
8    31400596
9    31450713
10   31469948
11   31447283
12   31453205
13   31462417
14   31462721
15   31461269
16   31463074
17   31473887
18   31461859
19   31464442
20   31419435
21   31466796
22   31470066
23   31459626
24   31465670
25   31469487
26   31460758
27   31461656
28   31464584
29   31458821
..        ...
847  31453638
848  31465192
849  31465081
850  31461649
851  31459766
852  31464005
853  31454512
854  31465920
855  31462206
856  31465054
857  31388303
858  31460691
859  31464701
860  31461978
861  31431257
862  31466693
863  31454902
864  31459347
865  31447118
866  31460412
867  31468612
868  31462342
869  31463259
870  31461950
871  31460980
872  31462956
873  31463572
874  31460407
875  31430117
876  31464444

[877 rows x 1 columns]

In [23]:
non_reg = []
for i in AA.Student_ID:
    Flag = False
    for j in Tested_reg.Student_ID:
        if i == j:
            Flag = True
            break
    if not Flag:
        non_reg.append(i)

In [25]:
len(non_reg)

359

In [19]:
""""AA_Dict = {}
for ID in range(AA):
    AA_Dict[AA[0:ID]] = AA[1:ID]
    """
AA.Student_ID[0]

31014572

In [20]:
AA.Email[0]

'nz1012861@gmail.com'

In [21]:
AA_Dict = {}
for ID in range(len(AA)):
    AA_Dict[AA.Student_ID[ID]] = AA.Email[ID]

In [26]:
reg = []
for i in AA.Student_ID:
    for j in Tested_reg.Student_ID:
        if i == j:
            reg.append(i)

In [27]:
len(reg)

363

In [28]:
A = 359 + 363

In [29]:
A

722

In [30]:
len(Tested_reg)

434

In [31]:
for i in reg:
    for j in non_reg:
        if i == j:
            print(i)

In [32]:
non_reg_non_online = []
for i in non_reg:
    Flag = False
    for j in online.S_ID:
        if i == j:
            Flag = True
            break
    if not Flag:
        non_reg_non_online.append(i)

In [33]:
len(non_reg_non_online)

295

In [36]:
email_to_blast =[]
for i in non_reg_non_online:
    email_to_blast.append(AA_Dict[i])

In [37]:
email_to_blast

['nz1012861@gmail.com',
 'ryanfagostinho@gmail.com',
 'student979student@gmail.com',
 'hermanfernandez14@gmail.com',
 'kgkandel@optonline.net',
 'chrisskchia@yahoo.com',
 'gus94369@gmail.com',
 'shaheedfive@gmail.com',
 'reeshagandhi123@gmail.com',
 'bkbkfk@yahoo.com',
 'bkbkfk@yahoo.com',
 'mbanos107@gmail.com',
 'avanibudoo@gmail.com',
 'nikhilsinha1212@gmail.com',
 'dylancorbett35@gmail.com',
 'evantang47@gmail.com',
 'davito1999@hotmail.com',
 'tonyramosmedia@gmail.com',
 'adsteelybrown@gmail.com',
 'nickmf@icloud.com',
 'nymets600@gmail.com',
 'eralfajora.co@gmail.com',
 'jinay0621@gmail.com',
 '1045smarvin@gmail.com',
 'svakhil00@gmail.com',
 'hemanth2355@gmail.com',
 'vrajeshalaguraj@gmail.com',
 'jamrt84@yahoo.com',
 'orionkresssan@westorangeschools.org',
 'sarah.qudah1@gmail.com',
 'surajsiv8@gmail.com',
 'bryantvega41@gmail.com',
 'justinswitten@gmail.com',
 'nmonticello18@stu.hpreg.org',
 'aaronbkellett@gmail.com',
 'colbydipaolo570@gmail.com',
 'naqeebr@yahoo.com',
 'joshli8963@gmail.com',
 'anthonyschillaci809@gmail.com',
 'jfire1235@gmail.com',
 'cameronscrosby@gmail.com',
 'thinurif@gmail.com',
 'jayson99@optimum.net',
 'romel.inoa@gmail.com',
 'anoushkakarnad@gmail.com',
 'nassimkhetir00@gmail.com',
 'jonathonkreinberg@gmail.com',
 'kyle.mclennan@optimum.net',
 'hurrderop@gmail.com',
 'rahishah.126@gmail.com',
 'shihab00@live.com',
 'uku_ray@yahoo.com',
 'mfe1236@gmail.com',
 'irwinracing10@gmail.com',
 'darshanpatel322@gmail.com',
 'drzjeremy30@hotmail.com',
 'elion.lita@student.rih.org',
 'smercado18@bgahs.org',
 'sammyeap@gmail.com',
 'jonperez102@gmail.com',
 'joshua.hoffmann@lps-students.org',
 'lamshinton@gmail.com',
 'zeang0822@gmail.com',
 'matt.aymar@hotmail.com',
 'andrewtawadros@yahoo.com',
 'elizabethkowalchuk@gmail.com',
 'erinfoody@gmail.com',
 'sebastiancfriend@gmail.com',
 'lckp112@gmail.com',
 'cculp99@gmail.com',
 'nicb3000@gmail.com',
 'tnberman07@gmail.com',
 'krunali2018@gmail.com',
 '18_atirro@s.wmrhsd.org',
 'kiistner24@hotmail.com',
 'oyitid@yahoo.com',
 'smirnovadenis@gmail.com',
 'jacobcua@gmail.com',
 'ericsfinck@gmail.com',
 'dacherdak@gmail.com',
 'laspisak@yahoo.com',
 'ashenoda@hcstonline.org',
 'robertkuna@icloud.com',
 'anmolsethi0699@gmail.com',
 'cmartins1671@gmail.com',
 'csegarra18@bgahs.org',
 'jamesquags@aim.com',
 'matthew.bacchi@gmail.com',
 'skailasanathan@ebnet.org',
 'shahharshil2830@gmail.com',
 'pierrymoise@gmail.com',
 'lky120037@gmail.com',
 'lukevu2000@gmail.com',
 'justin@thepetways.com',
 'vineetsridhar@gmail.com',
 'haadi.marashi@gmail.com',
 'schoppy@optonline.net',
 'lenriqu34@gmail.com',
 'johnmettry2000@gmail.com',
 'kitkat5938@gmail.com',
 'gshithesh@hotmail.com',
 'nyybmm@gmail.com',
 'vshah2799@gmail.com',
 'kushpatel438@gmail.com',
 'kushpatel438@gmail.com',
 'jaylincabrera10@gmail.com',
 'vickidom12@gmail.com',
 'mpothen18@pascack.org',
 'reverendod@students.spprep.org',
 '10012358@sbstudents.org',
 'abcdefgmaol.com@gmail.com',
 'naitam@ymail.com',
 'gilcarlos1914@gmail.com',
 'stevenyr116@gmail.com',
 'brandoncastillo384@gmail.com',
 'xrey0008@gmail.com',
 'jared_donnelly1@aol.com',
 'rymaxb@gmail.com',
 'nairi.arslan26@gmail.com',
 'khcaiazzo@gmail.com',
 'yashwee2000@gmail.com',
 'yonkersyankes@yahoo.com',
 'ponnor@gmail.com',
 'ranfis.francisco@gmail.com',
 'mmoussa202@gmail.com',
 'sean.wilson@donboscoprep.org',
 'diomedbr@pascack.org',
 'e.kazz@ymail.com',
 'bridgittelimaymanta@hotmail.com',
 'tarod811@gmail.com',
 'parth.agrawal@outlook.com',
 '180575@pcti.mobi',
 'h.zaki8300@gmail.com',
 'jake.nhan555@gmail.com',
 'kathleenskymancini@gmail.com',
 'dipenpatel644@gmail.com',
 'robert.richardson@mcstudent.org',
 'ghosal.sohini@yahoo.com',
 'travisprekop@yahoo.com',
 'goalloutcreative@icloud.com',
 'keithmontalvojr@ymail.com',
 'mmrozekmccourt18@bgahs.org',
 'dodoria80@hotmail.com',
 '18scottt@ptsdwebapps.com',
 'davidkatri1999@gmail.com',
 'amalsawab@gmail.com',
 'samanthaeschultz2018@gmail.com',
 'scottboys28@yahoo.com',
 'jssmitty909@gmail.com',
 'bretthelmkamp@yahoo.com',
 'krocky576@gmail.com',
 'taylorjdav@gmail.com',
 'cao20180049@student.nhvweb.net',
 'enzo.correa406@gmail.com',
 'dalal.kashish5@gmail.com',
 'miroslavfwork@gmail.com',
 '180449@pcti.mobi',
 'pradnya.desai0908@gmail.com',
 'jiannaccone@unioncatholic.org',
 'avarughese412@gmail.com',
 'hunt20180202@student.nhvweb.net',
 'spencerc211@verizon.net',
 'danilowiczkacper@gmail.com',
 'gferrer40@gmail.com',
 'mervyn.mathew@lps-students.org',
 'lanegriffis1967@gmail.com',
 'rodas23@yahoo.com',
 'swapnilp6200@gmail.com',
 'snair18@pthsd.net',
 'mw359@njit.edu',
 'jbramweg509@gmail.com',
 'abhatt531@gmail.com',
 'ualshehab@outlook.com',
 'zslm623@aol.com',
 'ericchan616@gmail.com',
 'denisahmemulic@yahoo.com',
 'wk46@njit.edu',
 'yumnaz@hotmail.com',
 'mdashy99@gmail.com',
 'aiwarimie@rosellecatholic.org',
 'steckerd@wctech.org',
 'pateldarshan374@gmail.com',
 'wlodarskim@students.spprep.org',
 'smtakla8110@gmail.com',
 'herzoi18@gmail.com',
 'sameer.qarizada98@gmail.com',
 'khugs775@gmail.com',
 'pratapakshay@hhschools.org',
 'krupari7@gmail.com',
 'caseyselenemedina@gmail.com',
 'nicolasgartner1@gmail.com',
 'kandarpa9@gmail.com',
 'cjspence080200@gmail.com',
 'demiankyrillos@gmail.com',
 'patrycja.ptak2321@gmail.com',
 'rashmi.venkatarama@gmail.com',
 'campbell.john@hermits.org',
 'jacob_martin@comcast.net',
 'annagmathew00@gmail.com',
 'luke.araza@gmail.com',
 'rddesai18@pthsd.net',
 'pranavgajera@gmail.com',
 'htai8903@gmail.com',
 'macauleykolonko@gmail.com',
 'lilibeth2400@gmail.com',
 'perbhatk@gmail.com',
 'xanastar2000@gmail.com',
 'andamir12@gmail.com',
 'jerrymccartenn@gmail.com',
 'psingh342001@gmail.com',
 'ajsavekin@gmail.com',
 'makayla.greenfield@gmail.com',
 'vishaalah99@yahoo.com',
 'sabila.hussain127@gmail.com',
 'whynot.pooja@gmail.com',
 'danigu99@hotmail.com',
 'paloma.almodovar@yahoo.es',
 'xeroxmercy01@gmail.com',
 'petercao@ymail.com',
 'nharabedian@gmail.com',
 'samqnzhou@gmail.com',
 'reynaldbarte@gmail.com',
 'llynken@gmail.com',
 'hollandgraphics@msn.com',
 'xxoxman@yahoo.com',
 'conor.coll@shrsd.org',
 'shana.m.dominique@gmail.com',
 'melzar@hcstonline.org',
 'dylanhigginsmdp@gmail.com',
 'hjrmesa@gmail.com',
 'saqlainsattar23@yahoo.com',
 'kerimsever23@gmail.com',
 'ryanszoja24@gmail.com',
 'pv44400@gmail.com',
 'adriancejoseph@gmail.com',
 'drew.diehl@yahoo.com',
 'descobar1732@gmail.com',
 'sohailabouelkhair1191@gmail.com',
 'jagness21@yahoo.com',
 'aagu1990@gmail.com',
 'joshuasuh33@yahoo.com',
 'brianm2017@hotmail.com',
 'jvilcarino101511@hotmail.com',
 'kevinvelezdms@gmail.com',
 'jeroduarte01@gmail.com',
 'parass2501@gmail.com',
 'z1315521294@gmail.com',
 'nescobar18@stu.hpreg.org',
 'sestime6@gmail.com',
 'kevrey494@gmail.com',
 'kyrollosgergis@yahoo.com',
 'akovanxhi@gmail.com',
 'srobcrowell@gmail.com',
 'kotarooi019@gmail.com',
 'hanaqvi18@pthsd.net',
 'dragandominik1@gmail.com',
 'martingdaskalov@yahoo.com',
 'ximena.m1512@hotmail.com',
 'eaglesrule2000@gmail.com',
 'nwosuudo@yahoo.com',
 'lucas@lucasbastos.com',
 'aya975@gmail.com',
 'phil.iosue@gmail.com',
 'sadeeqs@icloud.com',
 'hunghoang20700@gmail.com',
 'adhamsamour6@gmail.com',
 'alihassan6457@gmail.com',
 'ppatel9200@gmail.com',
 'ratakonda48@gmail.com',
 'shounakbosco@gmail.com',
 'akhil.vaswani1@gmail.com',
 'timmyli080699@gmail.com',
 'cannonj35@gmail.com',
 'tmironovici@gmail.com',
 'haitham13.giants@gmail.com',
 'joel83100@gmail.com',
 'dominator2486@gmail.com',
 'mlwowski@hcrhs.org',
 'vicocinio@gmail.com',
 'tahayounis3@gmail.com',
 'wbondiv12@gmail.com',
 'judyzuo124@gmail.com',
 '1jamescoll@gmail.com',
 'legoman9994@gmail.com',
 'anmorales@ctemc.org',
 'ammadbajwa77@gmail.com',
 'gian.ordonez@gmail.com',
 'ghanshyampatel123r@gmail.com',
 'cosmicpm24@gmail.com',
 'bendejesus123@gmail.com',
 'amaan.rajguru@gmail.com',
 'whyandwonder@yahoo.com',
 'jcranmer34@gmail.com',
 'antoniousshaker@gmail.com',
 'fuschc4@gmail.com']

In [42]:
with open('Emails.txt','w') as f:
    for e in email_to_blast:
        f.write(e+',')

In [43]:
on_reg = pd.read_csv('online_reg_tes.csv')

In [44]:
on_reg.head()

       S_ID
0  31459413
1  31447208
2  31461898
3  31459561
4  31469550

In [46]:
non_online_reg = []
for i in online.S_ID:
    Flag = False
    for j in on_reg.S_ID:
        if i == j:
            Flag = True
            break
    if not Flag:
        non_online_reg.append(i)

In [47]:
len(non_online_reg)

843

In [48]:
len(on_reg)

34

In [51]:
Online_non_reg_AA = []
Online_non_reg_CC = []
for i in non_online_reg:
    if i in AA_Dict:
        Online_non_reg_AA.append(i)
    else:
        Online_non_reg_CC.append(i)

In [52]:
len(Online_non_reg_AA)

65

In [53]:
len(Online_non_reg_CC)

778

In [54]:
b = 778 + 65

In [55]:
b

843